strin = input("enter a string >> ")
strinLen = len(strin)

strin = strin.replace("A", "")
strin = strin.replace("B", "")
strin = strin.replace("C", "")
strin = strin.replace("D", "")
strin = strin.replace("E", "")
strin = strin.replace("F", "")
strin = strin.replace("G", "")
strin = strin.replace("H", "")
strin = strin.replace("I", "")
strin = strin.replace("J", "")
strin = strin.replace("K", "")
strin = strin.replace("L", "")
strin = strin.replace("M", "")
strin = strin.replace("N", "")
strin = strin.replace("O", "")
strin = strin.replace("P", "")
strin = strin.replace("Q", "")
strin = strin.replace("R", "")
strin = strin.replace("S", "")
strin = strin.replace("T", "")
strin = strin.replace("U", "")
strin = strin.replace("V", "")
strin = strin.replace("W", "")
strin = strin.replace("X", "")
strin = strin.replace("Y", "")
strin = strin.replace("Z", "")
newLen = len(strin)

print(strinLen - newLen)